name: Deploy PHP app to Azure Web App

on:
  push:
    branches:
      - main  # Triggers deployment when pushing to main
  workflow_dispatch:  # Allows manual trigger in GitHub Actions

env:
  AZURE_WEBAPP_NAME: healthbudddy  # 👈 your Azure App Service name
  AZURE_WEBAPP_PACKAGE_PATH: '.'   # 👈 path to PHP files (root of repo)
  PHP_VERSION: '8.2'               # 👈 PHP version for setup (optional but good practice)

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: php-app
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: php-app

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
